server:
  port: 1235
  ssl:
    enabled: true
    key-store: classpath:server.p12
    key-store-type: PKCS12
    key-store-password: changeit
  http2:
    enabled: true

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0 # for dev: trace everything; lower in prod, e.g., 0.1